<script setup lang="ts">
import { ref, computed } from 'vue'
import {
  analyzeDetailedTimingAgainstCTA,
  computePixelClockForTargetRate,
  computeRefreshRate,
  generateCVTDetailedTiming,
  generateCVTDetailedTimingForTarget,
  generateDetailedTimingFromVIC,
  type CVTTimingInput,
  type DetailedTiming,
  type DetailedTimingDescriptor,
} from 'edidts'
import { roundedRefreshRate } from '@/components/common/timingLabels'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import DetailedTimingFields from './DetailedTimingFields.vue'
import VicPicker from './VicPicker.vue'
import {
  CVT_BLANKING_LABELS,
  CVT_PRESET_ENTRIES,
  DTD_PIXEL_CLOCK_MAX,
  REFRESH_RATE_MAX,
  REFRESH_RATE_MIN,
  TIMING_MODE_OPTIONS,
  generateTimingFromPreset,
  getTimingEditorState,
  modeToBlankingMode,
  type TimingEditorMode,
} from '@/composables/useTimingEditorState'

/**
 * Shared detailed-timing card chrome: header (Timing N, resolution×refresh,
 * pixel-clock subtitle, Mode selector, expand toggle), a Preset picker, the
 * top controls row (Pixel Clock / Refresh / Margins), and the
 * DetailedTimingFields editor. Consumed by the EDID base-block descriptor view
 * (EDIDDetailedDescriptors.vue) and the CTA-861 DTD view (CTADetailedTimings.vue),
 * which share the same DetailedTiming field set via the common DTD codec.
 *
 * Refresh is derived from the single lib source {@link computeRefreshRate} —
 * never recomputed locally. Consumer-specific chrome is supplied via slots:
 *   - #details: the expanded body after the field editor (H/V summary grid,
 *     CTA-861 reference, CVT calculator — these differ per consumer)
 *
 * Emits `update` with a dotted field path and new value, forwarded from
 * DetailedTimingFields; the owning component mutates the matching timing
 * instance and the useEDID computed re-encodes.
 *
 * Timing mode: an authoring-mode selector (Custom / CVT / CVT-RB / CVT-RBv2 /
 * Target Refresh Rate / CTA-861) drives field locking and CVT regeneration. In
 * a CVT mode the derived geometry is recomputed via
 * {@link generateCVTDetailedTiming} from the free parameters (H/V active, H/V
 * image size, interlaced, plus editor-only refresh rate and margins) and
 * written back onto the existing reactive DTD in place. The mode
 * and the CVT-only params (refresh rate, margins) are editor state held in
 * {@link useTimingEditorState} — never serialized into the EDID bytes.
 *
 * In Custom mode the Refresh input is an editable target that derives only the
 * pixel clock from the user-owned geometry, quantized to the DTD's 10 kHz
 * clock resolution; the geometry itself is never touched.
 */
const props = withDefaults(defineProps<{
  timing: DetailedTiming
  index: number
  /** Force the expanded body on (e.g. a focused single-timing view). */
  forceExpand?: boolean
  /** Show the "Show/Hide details" toggle button. */
  showToggle?: boolean
  /** Positional "Native" badge (CTA-861: the first nativeFormats DTDs are
   *  native — CTAHeaderFlags's picker owns the declaration). */
  native?: boolean
}>(), { forceExpand: false, showToggle: true, native: false })

const emit = defineEmits<{
  update: [field: string, value: unknown]
}>()

const expanded = ref(false)
const isExpanded = computed(() => props.forceExpand || expanded.value)

/** True when the last regeneration was refused because the CVT generator's
 *  pixel clock exceeded the 16-bit 10 kHz DTD field (655.35 MHz) — e.g. a
 *  target refresh rate too high for the active resolution.
 *  Cleared at the top of every regeneration attempt. */
const pixelClockOverflow = ref(false)

/** True when a Custom-mode target rate could not be applied because the
 *  recomputed pixel clock exceeds the 16-bit 10 kHz DTD field (655.35 MHz) —
 *  the timing was left unchanged. */
const customRateOverflow = ref(false)
/** True once a Custom-mode target rate has been applied to the timing, gating
 *  the achieved-vs-target readout. */
const customTargetApplied = ref(false)

const refresh = computed(() => computeRefreshRate(props.timing))

/** Editor-only authoring state for this DTD (mode + CVT free params). */
const state = getTimingEditorState(props.timing)
const isCVTMode = computed(() => state.mode !== 'custom' && state.mode !== 'cea-861')
/** CEA-861 authoring mode: a VIC owns the timing geometry. */
const cea861 = computed(() => state.mode === 'cea-861')
/** Custom authoring mode: the user owns the geometry; the Refresh input is a
 *  target that derives only the pixel clock from it. */
const customMode = computed(() => state.mode === 'custom')
/** "Target refresh rate" authoring mode: the refresh input is the
 *  user's target; the achieved rate is derived from the generated bytes. */
const targetMode = computed(() => state.mode === 'target')
/** Margins only applies to standard CVT — RB and target modes ignore it. */
const showMargins = computed(() => state.mode === 'cvt')

/** Deviation of the achieved rate from the target in "target" mode — the
 *  pixel clock is quantized up to the next 0.25 MHz CVT step, so the achieved
 *  rate is always ≥ target by a small amount. */
const refreshDelta = computed(() => round2(refresh.value - state.refreshRate))

/** Blanking variant the target-rate solver last picked — shown in
 *  the target-mode readout so the variant that hit the rate is visible. */
const targetVariantLabel = computed(() =>
  state.targetBlankingMode ? CVT_BLANKING_LABELS[state.targetBlankingMode] : null,
)

// `disabled:` variants follow the shadcn-vue SelectTrigger pattern; only the
// preset picker is ever disabled, the mode select sharing this class is not.
const modeSelectClass =
  'h-7 rounded-md border border-input bg-transparent dark:bg-input/30 px-2 text-xs shadow-xs outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50'

/** Controlled value of the Preset `<select>` — held only to reset the picker to
 * its placeholder after a load (it is a one-shot "load a starting point"
 * control, not a persistent selection). */
const selectedPreset = ref('')

/** App-standard Switch row treatment (matches CTAHeaderFlags / CTAVideoCapability):
 * transparent border, hover wash, non-uppercase muted label. */
const switchRowClass =
  'flex items-center justify-between gap-2 rounded-md border border-transparent px-3 py-2 hover:bg-muted/50 transition-colors'

/** DTD fields the CVT generator derives from the free parameters. */
const FREE_PARAM_FIELDS = new Set([
  'horizontalActive',
  'verticalActive',
  'horizontalImageSize',
  'verticalImageSize',
  'flags.interlaced',
])

function toggle() {
  expanded.value = !expanded.value
}

function round2(n: number): number {
  return Number.isFinite(n) ? Math.round(n * 100) / 100 : 0
}

/**
 * Write a generated timing's derived fields onto the reactive DTD proxy in
 * place. The free parameters (active, image size, interlaced) are the generator
 * inputs and are left as the user set them; everything else is owned by the
 * generator.
 */
function writeDerivedFields(gen: DetailedTimingDescriptor): void {
  props.timing.pixelClock = gen.pixelClock
  props.timing.horizontalBlanking = gen.horizontalBlanking
  props.timing.verticalBlanking = gen.verticalBlanking
  props.timing.horizontalSyncOffset = gen.horizontalSyncOffset
  props.timing.horizontalSyncWidth = gen.horizontalSyncWidth
  props.timing.verticalSyncOffset = gen.verticalSyncOffset
  props.timing.verticalSyncWidth = gen.verticalSyncWidth
  props.timing.horizontalBorder = gen.horizontalBorder
  props.timing.verticalBorder = gen.verticalBorder
  props.timing.flags.interlaced = gen.flags.interlaced
  props.timing.flags.syncType = gen.flags.syncType
  props.timing.flags.stereoMode = gen.flags.stereoMode
  props.timing.flags.hSyncPolarity = gen.flags.hSyncPolarity
  props.timing.flags.vSyncPolarity = gen.flags.vSyncPolarity
}

/**
 * Recompute the DTD's derived geometry from the current free parameters and the
 * editor CVT inputs (refresh rate, margins), writing the result onto the
 * existing reactive timing instance in place. No-ops (without throwing) when
 * the active resolution or target refresh rate is zero/invalid — e.g. a fresh
 * all-zero DTD before the user enters values.
 *
 * In "target refresh rate" mode the blanking variant is not fixed: the editor
 * asks the CVT calculator to solve across all three variants (standard / RB /
 * RBv2) under the 655.35 MHz DTD clock limit and writes the one whose achieved
 * rate lands closest to the target. When no variant fits, the
 * timing is left untouched and the overflow warning is shown.
 *
 * After mutating, emits a single `update` for `pixelClock` so the owning
 * component's `setByPath` reassigns the enclosing `detailedTimings` array — the
 * documented encode trigger. The pure encode then re-reads
 * the mutated-in-place element and re-encodes.
 */
function regenerate(): void {
  pixelClockOverflow.value = false
  const horizontalActive = Math.round(props.timing.horizontalActive)
  const verticalActive = Math.round(props.timing.verticalActive)
  const refreshRate = round2(state.refreshRate)
  if (horizontalActive <= 0 || verticalActive <= 0 || refreshRate <= 0) return

  const input: Omit<CVTTimingInput, 'blankingMode'> = {
    horizontalActive,
    verticalActive,
    refreshRate,
    interlaced: props.timing.flags.interlaced,
    margins: state.margins,
    horizontalImageSize: Math.round(props.timing.horizontalImageSize),
    verticalImageSize: Math.round(props.timing.verticalImageSize),
  }

  if (targetMode.value) {
    // Target-rate solve: the calculator picks the blanking variant; null means
    // no variant hits the target within the DTD pixel-clock limit.
    const gen = generateCVTDetailedTimingForTarget(input, DTD_PIXEL_CLOCK_MAX)
    if (!gen) {
      pixelClockOverflow.value = true
      return
    }
    writeDerivedFields(gen.timing)
    state.targetBlankingMode = gen.blankingMode
  } else {
    const blankingMode = modeToBlankingMode(state.mode)
    if (!blankingMode) return
    const gen = generateCVTDetailedTiming({ ...input, blankingMode })

    // The DTD pixel clock is a 16-bit 10 kHz field (max 655.35 MHz). The
    // generator has no notion of that limit, so refuse an unencodable timing
    // instead of writing a clock the encoder would silently truncate (the
    // Custom-mode input already clamps to this range; this extends the
    // clamp to the generative modes).
    if (gen.pixelClock > DTD_PIXEL_CLOCK_MAX) {
      pixelClockOverflow.value = true
      return
    }
    writeDerivedFields(gen)
  }

  emit('update', 'pixelClock', props.timing.pixelClock)
}

/**
 * Load a CVT preset onto the current DTD as a complete starting point. Unlike
 * {@link regenerate} (which preserves the user-set free parameters), this
 * overwrites every DetailedTiming field with the preset's generated timing,
 * generated under the variant currently selected in the Mode selector — the
 * preset owns only the timing (resolution/refresh), never the mode.
 * Seeds the CVT refresh-rate input from the preset, then emits `update` for
 * `pixelClock` so the owning mutator reassigns the enclosing `detailedTimings`
 * array (the documented encode trigger). The picker resets to its placeholder
 * afterwards — it is a one-shot "load a starting point" control, not a
 * persistent selection (subsequent field edits would diverge from any fixed
 * label).
 */
function onPresetChange(event: Event): void {
  const key = (event.target as HTMLSelectElement).value
  if (!key) return
  const blankingMode = modeToBlankingMode(state.mode)
  if (!blankingMode) return // unreachable: the picker is disabled in Custom/CEA-861 modes
  const { timing: gen, refreshRate } = generateTimingFromPreset(key, blankingMode)

  props.timing.pixelClock = gen.pixelClock
  props.timing.horizontalActive = gen.horizontalActive
  props.timing.horizontalBlanking = gen.horizontalBlanking
  props.timing.verticalActive = gen.verticalActive
  props.timing.verticalBlanking = gen.verticalBlanking
  props.timing.horizontalSyncOffset = gen.horizontalSyncOffset
  props.timing.horizontalSyncWidth = gen.horizontalSyncWidth
  props.timing.verticalSyncOffset = gen.verticalSyncOffset
  props.timing.verticalSyncWidth = gen.verticalSyncWidth
  props.timing.horizontalImageSize = gen.horizontalImageSize
  props.timing.verticalImageSize = gen.verticalImageSize
  props.timing.horizontalBorder = gen.horizontalBorder
  props.timing.verticalBorder = gen.verticalBorder
  props.timing.flags.interlaced = gen.flags.interlaced
  props.timing.flags.syncType = gen.flags.syncType
  props.timing.flags.stereoMode = gen.flags.stereoMode
  props.timing.flags.hSyncPolarity = gen.flags.hSyncPolarity
  props.timing.flags.vSyncPolarity = gen.flags.vSyncPolarity

  state.refreshRate = refreshRate
  state.margins = false

  // "Target refresh rate" mode re-solves the preset under the target rules:
  // the preset write above uses standard CVT, but the mode's contract is the
  // closest-achievable variant (e.g. a 4K120 preset lands on RBv2).
  if (targetMode.value) regenerate()

  emit('update', 'pixelClock', props.timing.pixelClock)
  selectedPreset.value = ''
}

function onModeChange(event: Event): void {
  const mode = (event.target as HTMLSelectElement).value as TimingEditorMode
  state.mode = mode
  if (mode === 'cea-861') {
    // CEA-861 mode: the VIC owns the timing. If the DTD already matches a VIC
    // (e.g. it was authored from one), pre-select it so the picker reflects the
    // current bytes — no rewrite is needed in that case. Otherwise leave the
    // picker on its placeholder and let the user pick a VIC to snap to.
    if (state.selectedVic == null) {
      const match = analyzeDetailedTimingAgainstCTA(props.timing as DetailedTimingDescriptor).matchVic
      if (match) state.selectedVic = match.vic
    }
    return
  }
  if (mode === 'custom') {
    // Seed the target input from the DTD's achieved rate so a first edit starts
    // from the present timing; Custom owns the geometry, so
    // there is nothing to regenerate.
    state.refreshRate = round2(computeRefreshRate(props.timing))
    customRateOverflow.value = false
    customTargetApplied.value = false
    return
  }
  // Seed the CVT refresh-rate input from the DTD's present geometry so the
  // first regeneration stays at the current rate; reset margins (std-only).
  state.refreshRate = round2(computeRefreshRate(props.timing))
  state.margins = false
  regenerate()
}

/**
 * Apply a CTA-861 VIC to the current DTD: snap every timing field to the VIC's
 * canonical geometry (written onto the reactive DTD in place, like
 * {@link onPresetChange}), record the selection in editor state, and emit
 * `update` for `pixelClock` so the owning mutator reassigns the enclosing
 * `detailedTimings` array (the documented encode trigger). Image size is
 * preserved — it is display-specific, not a VIC property, and stays read-only
 * in CEA-861 mode. A null selection (picker cleared) is ignored.
 */
function onVICSelect(vic: number | null): void {
  if (vic == null) return
  const gen = generateDetailedTimingFromVIC(vic)

  props.timing.pixelClock = gen.pixelClock
  props.timing.horizontalActive = gen.horizontalActive
  props.timing.horizontalBlanking = gen.horizontalBlanking
  props.timing.verticalActive = gen.verticalActive
  props.timing.verticalBlanking = gen.verticalBlanking
  props.timing.horizontalSyncOffset = gen.horizontalSyncOffset
  props.timing.horizontalSyncWidth = gen.horizontalSyncWidth
  props.timing.verticalSyncOffset = gen.verticalSyncOffset
  props.timing.verticalSyncWidth = gen.verticalSyncWidth
  props.timing.horizontalBorder = gen.horizontalBorder
  props.timing.verticalBorder = gen.verticalBorder
  props.timing.flags.interlaced = gen.flags.interlaced
  props.timing.flags.syncType = gen.flags.syncType
  props.timing.flags.stereoMode = gen.flags.stereoMode
  props.timing.flags.hSyncPolarity = gen.flags.hSyncPolarity
  props.timing.flags.vSyncPolarity = gen.flags.vSyncPolarity

  state.selectedVic = vic
  emit('update', 'pixelClock', props.timing.pixelClock)
}

/**
 * Custom-mode target-rate apply: derive ONLY the pixel clock from
 * the user-owned geometry at the typed rate
 * (hTotal × vTotal × rate, halved for interlaced field rates), leaving every
 * other field — blanking, syncs, borders — untouched. The result is quantized
 * to the DTD's native 10 kHz clock resolution inside
 * {@link computePixelClockForTargetRate}; a clock that does not fit the
 * 16-bit field leaves the timing unchanged and shows the overflow warning
 * instead of writing a value the encoder would silently truncate. A fresh
 * all-zero DTD (no usable geometry yet) no-ops without a warning.
 */
function applyCustomTargetRate(value: number): void {
  customRateOverflow.value = false
  state.refreshRate = value
  const hTotal = Math.round(props.timing.horizontalActive) + Math.round(props.timing.horizontalBlanking)
  const vTotal = Math.round(props.timing.verticalActive) + Math.round(props.timing.verticalBlanking)
  if (hTotal <= 0 || vTotal <= 0) return // fresh/empty DTD — nothing to solve yet
  const clock = computePixelClockForTargetRate(props.timing, value, DTD_PIXEL_CLOCK_MAX)
  if (clock == null) {
    customRateOverflow.value = true
    return
  }
  props.timing.pixelClock = clock
  customTargetApplied.value = true
  emit('update', 'pixelClock', clock)
}

function onRefreshChange(v: string | number): void {
  const parsed = typeof v === 'number' ? v : Number(v)
  let value = Number.isFinite(parsed) ? round2(parsed) : 0
  // "Target refresh rate" mode clamps the target into the sensible bounds so
  // the input cannot even ask for an unachievable rate; the
  // plain CVT modes keep the legacy behaviour (0 = no-op until a real rate
  // is typed, e.g. while seeding a fresh DTD).
  if (targetMode.value || customMode.value) {
    value = Math.max(REFRESH_RATE_MIN, Math.min(REFRESH_RATE_MAX, value))
  }
  if (customMode.value) {
    applyCustomTargetRate(value)
    return
  }
  state.refreshRate = value
  regenerate()
}

/**
 * Pixel Clock edit (Custom mode only — the input is disabled in CVT modes where
 * the generator owns it). pixelClock is in MHz with 0.01 MHz resolution (10 kHz
 * units) and a 16-bit field, so round to 2 dp and clamp to the encodable
 * 0–655.35 MHz range — the encoder would silently truncate anything
 * above 655.35.
 */
function onPixelClock(v: string | number): void {
  const parsed = typeof v === 'number' ? v : Number(v)
  const rounded = Number.isFinite(parsed) ? Math.round(parsed * 100) / 100 : 0
  emit('update', 'pixelClock', Math.max(0, Math.min(655.35, rounded)))
}

function onMarginsChange(v: boolean): void {
  state.margins = v
  regenerate()
}

/**
 * Forward field edits from DetailedTimingFields. In Custom mode the edit goes
 * straight through to the owning mutator as before. In a CVT mode only the free
 * parameters are editable (the rest are disabled); applying a free param then
 * regenerating the derived geometry keeps the DTD consistent with the mode.
 */
function onFieldUpdate(field: string, value: unknown): void {
  if (!isCVTMode.value) {
    emit('update', field, value)
    return
  }
  if (!FREE_PARAM_FIELDS.has(field)) return // locked/derived field — ignore
  applyFreeParam(field, value)
  regenerate()
}

function applyFreeParam(field: string, value: unknown): void {
  if (field.startsWith('flags.')) {
    const flag = field.slice('flags.'.length)
    ;(props.timing.flags as unknown as Record<string, unknown>)[flag] = value
  } else {
    ;(props.timing as unknown as Record<string, unknown>)[field] = value
  }
}
</script>

<template>
  <div class="rounded-2xl border border-border/60 bg-card shadow-sm scroll-mt-6">
    <div class="flex flex-wrap items-start gap-4 border-b border-border/40 p-4">
      <div>
        <p class="text-[11px] uppercase tracking-wide text-muted-foreground">
          Timing {{ index + 1 }}
          <span
            v-if="native"
            class="ml-1.5 inline-flex items-center rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-emerald-600 dark:text-emerald-400"
          >Native</span>
        </p>
        <p class="text-lg font-semibold text-foreground">
          {{ timing.horizontalActive }}×{{ timing.verticalActive }}{{ timing.flags.interlaced ? 'i' : 'p' }} ·
          {{ roundedRefreshRate(timing) }} Hz
        </p>
        <p class="text-xs text-muted-foreground">{{ timing.pixelClock.toFixed(2) }} MHz pixel clock</p>
      </div>
      <div class="ml-auto flex flex-col items-end gap-2">
        <div class="flex flex-wrap items-center gap-3">
          <!-- Preset picker: load a CVT preset onto the current DTD as a starting
               point (overwrites all fields, generated under the currently
               selected mode's CVT variant — the mode itself is untouched). Only
               meaningful in a CVT mode, so it is disabled in Custom and CEA-861
               modes. A one-shot control — resets to the placeholder after each
               load. -->
          <select
            :class="modeSelectClass"
            aria-label="Load preset"
            :value="selectedPreset"
            :disabled="!isCVTMode"
            @change="onPresetChange"
          >
            <option value="">Load preset…</option>
            <option v-for="preset in CVT_PRESET_ENTRIES" :key="preset.key" :value="preset.key">{{ preset.label }}</option>
          </select>
          <select
            :class="modeSelectClass"
            aria-label="Timing mode"
            :value="state.mode"
            @change="onModeChange"
          >
            <option v-for="opt in TIMING_MODE_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</option>
          </select>
          <button
            v-if="showToggle"
            type="button"
            class="text-xs font-semibold text-foreground/80 hover:text-primary"
            @click="toggle"
          >
            {{ isExpanded ? 'Hide details' : 'Show details' }}
          </button>
        </div>
        <!-- CEA-861 mode: the VIC picker lives under the preset/mode selectors
             (it is the sole free-parameter control — every DTD field is locked
             to the VIC's bytes). Kept out of the edit-fields area per UX. -->
        <VicPicker
          v-if="cea861"
          class="w-full sm:w-72"
          :model-value="state.selectedVic"
          @update:model-value="(v) => onVICSelect(v)"
        />
      </div>
    </div>
    <div
      v-if="isExpanded"
      class="border-t border-border/40 p-4 text-xs text-muted-foreground"
    >
      <!-- Top controls row: Pixel Clock | Refresh Rate | Margins. Always
           rendered as a 3-column grid so the layout never reflows between
           modes. Pixel Clock is editable in Custom mode and disabled in CVT
           modes (generator owns it) and CEA-861 mode (the VIC owns it); the
           CEA-861 VIC picker lives in the header, not here. Refresh Rate is
           the editable CVT generator input and, in Custom mode, an editable
           target that derives only the pixel clock from the user-owned
           geometry; in CEA-861 mode it stays a read-only mirror of
           the VIC's derived rate. Margins is enabled only for standard CVT. -->
      <div class="mb-4 grid gap-3 sm:grid-cols-3">
        <label class="flex flex-col gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Pixel Clock (MHz)
          <Input
            type="number"
            :min="0"
            :max="655.35"
            :step="0.01"
            :disabled="isCVTMode || cea861"
            :model-value="timing.pixelClock"
            @update:model-value="(v) => onPixelClock(v)"
          />
        </label>
        <label class="flex flex-col gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          {{ targetMode || customMode ? 'Target Refresh Rate (Hz)' : 'Refresh Rate (Hz)' }}
          <Input
            type="number"
            :min="targetMode || customMode ? REFRESH_RATE_MIN : 0"
            :max="REFRESH_RATE_MAX"
            :step="0.01"
            :disabled="cea861"
            :model-value="cea861 ? refresh : state.refreshRate"
            @update:model-value="(v) => onRefreshChange(v)"
          />
        </label>
        <label :class="switchRowClass">
          <span class="text-xs text-muted-foreground">Margins (1.8%)</span>
          <Switch
            :model-value="state.margins"
            :disabled="!showMargins"
            @update:model-value="(v: boolean) => onMarginsChange(v)"
          />
        </label>
      </div>

      <!-- "Target refresh rate" mode readout: the
           editor solves across the CVT blanking variants and writes the one
           whose quantized pixel clock lands closest to the target — show the
           chosen variant, the achieved rate and the deviation, plus a warning
           when no variant can hit the target within the 16-bit DTD clock field.
           Custom mode shows the same achieved-vs-target readout (without the
           variant — the geometry is user-owned) and its own overflow warning. -->
      <div
        v-if="targetMode || pixelClockOverflow || (customMode && (customTargetApplied || customRateOverflow))"
        class="mb-4 space-y-1"
      >
        <p v-if="targetMode" class="text-xs text-muted-foreground">
          Achieved refresh rate: <span class="font-mono text-foreground">{{ refresh.toFixed(2) }} Hz</span>
          at target {{ state.refreshRate }} Hz
          <template v-if="targetVariantLabel">via {{ targetVariantLabel }} blanking</template>
          (Δ {{ refreshDelta >= 0 ? '+' : '' }}{{ refreshDelta.toFixed(2) }} Hz from pixel-clock quantization)
        </p>
        <p v-if="customMode && customTargetApplied" class="text-xs text-muted-foreground">
          Achieved refresh rate: <span class="font-mono text-foreground">{{ refresh.toFixed(2) }} Hz</span>
          at target {{ state.refreshRate }} Hz
          (Δ {{ refreshDelta >= 0 ? '+' : '' }}{{ refreshDelta.toFixed(2) }} Hz from pixel-clock quantization)
        </p>
        <p v-if="pixelClockOverflow" class="text-xs text-destructive">
          Target refresh rate too high: no CVT blanking variant (CVT / CVT-RB / CVT-RBv2) hits the target
          within the 655.35 MHz DTD pixel-clock limit — the timing was left unchanged.
          Lower the target or the resolution.
        </p>
        <p v-if="customRateOverflow" class="text-xs text-destructive">
          Target refresh rate too high: the recomputed pixel clock exceeds the 655.35 MHz DTD
          pixel-clock limit — the timing was left unchanged.
          Lower the target or the resolution.
        </p>
      </div>

      <div class="mb-4">
        <p class="text-[11px] uppercase tracking-wide mb-2 text-foreground/80">Edit Fields</p>
        <DetailedTimingFields
          :timing="timing"
          :mode="state.mode"
          @update="(field: string, value: unknown) => onFieldUpdate(field, value)"
        />
      </div>
      <slot name="details" />
    </div>
  </div>
</template>